### ISSUE TITLE
Truly Impressed by Your Script—May I Ask a Few Questions?

### ISSUE THREAD

**Issue by Tribbiani** [junjiem/dify-plugin-repackaging#5]
I also read the source code of dify-plugin-daemon, but at first, I couldn't quite figure out how the framework handles plugins—possibly because I am not very familiar with Go. 

After reading your script and revisiting the source code, I realized that the core logic for adding a plugin in the dify framework is essentially about installing the plugin's dependencies via pip.

And your script cleverly avoids the need for a network connection by using locally wheels instead.

I am really curious, how did u approach reading the source code and manage to identify the key logic for implementing the script?

I would truly love to learn from your experience.

**Comment by junjiem** [comment]
> I also read the source code of dify-plugin-daemon, but at first, I couldn't quite figure out how the framework handles plugins—possibly because I am not very familiar with Go.
> 
> After reading your script and revisiting the source code, I realized that the core logic for adding a plugin in the dify framework is essentially about installing the plugin's dependencies via pip.
> 
> And your script cleverly avoids the need for a network connection by using locally wheels instead.
> 
> I am really curious, how did u approach reading the source code and manage to identify the key logic for implementing the script?
> 
> I would truly love to learn from your experience.

I read little source code of dify-plugin-daemon, and I don't know Go language.  The basic logic can be discovered by experimenting.  Sorry my English is not good. All I want to say is more try.

**Comment by SulphuricOrange** [comment]
After I run your .sh script, I inspect the output package file. It seems that by modifying the requirements.txt to let pip installation use .whl file in the /wheels/ folder, which could avoid downloading dependencies through internet. I hope I correctly understanded the underlying logic of this shell script.
我运行了您的脚本，并查看了输出的文件，看起来这个脚本通过修改了requirements.txt，并将下载的whl文件放在wheels文件夹内，这使得plugin deamon在安装插件载入依赖时使用了本地的文件。我希望我的理解是正确的。
Which infers another way, still use pip to install dependencies. But rather modify the docker-compose YAML file to let pip install from a pypiserver that you would like to deploy on you Linux server, with all .whl files that could satisfies your plugin's requirements.txt. (also includes dependencies of dependencies, and they will need to be correct binary for linux you use. --platorm manylinux2014）
This might involve modifications to the YAML file like these:
这也使得另一种方法也是可行的，但是其需要修改docker-compose.yaml文件，并将其中的PIP URL地址改为一个pypiserver的内网镜像地址（假设放在您的Linux服务器上）。同时还需要准备好您插件所需要的一切whl依赖文件（包括依赖的依赖，以及有些二进制需要与Linux内核版本相匹配，如使用 --platorm manylinux2014）
```YAML
  # plugin daemon
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.7-local
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      ...
      PYTHON_ENV_INIT_TIMEOUT: ${PLUGIN_PYTHON_ENV_INIT_TIMEOUT:-120}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
```
Here you need to set the URL to someting like: http://192.168.1.100:8080/simple/, which dependes on the host that you run dify(assuming using docker)
You may also want to adjust timeout settings, which could increasing success probability under slow connections (even for dify that connect to public internet)
这里需要将URL设置为你的镜像地址和端口，如果你使用docker跑dify的话可能是需要暴露网络的。上面两条超时设置也可以改，理论上改超时设置可以提高低速网络连接的安装成功率（外网也是）

Anyway, thanks to your .sh creation! You really saved my assigned task from my boss!
无论如何感谢您，您的巧妙发明拯救我公司牢大派给我的任务（他们想用dify做文档生成）
